### ISSUE TITLE
请问一下，您参加车牌识别大赛 的数据集能分享一下吗？有链接下载吗？加了您的qq。我测试一下，谢谢

### ISSUE THREAD

**Issue by QQ2737499951** [Liuyubao/PlateRecognition#1]
请问一下，您参加车牌识别大赛 的数据集能分享一下吗？有链接下载吗？加了您的qq。我测试一下，谢谢

**Comment by Liuyubao** [comment]
您好，我没有参加车牌识别大赛，应该是搞错了。
关于模型的训练可以参考https://github.com/armaab/hyperlpr-train
我的路径底下有几张上传的图片，可供测试。

**Comment by little2Rabbit** [comment]
@Liuyubao 您提供的这个训练模型，我训练了但是和ocr_plate_all_gru.h5这个模型的网络结构不同，训练完了报如下错误：
ValueError: You are trying to load a weight file containing 11 layers into a model with 13 layers.

**Comment by Liuyubao** [comment]
试调整layers层数，使得输出model一致。
