### ISSUE TITLE
您好，如果我想训练自己的模型，怎样重新训练model/cascade.xml", "model/model12.h5", "model/ocr_plate_all_gru.h5这3个模型？

### ISSUE THREAD

**Issue by EllisHui** [Liuyubao/PlateRecognition#5]

**Comment by Liuyubao** [comment]
模型训练可参考：https://github.com/LCorleone/A-Simple-Chinese-License-Plate-Generator-and-Recognition-Framework

**Comment by Liuyubao** [comment]
https://github.com/armaab/hyperlpr-train
